config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root 'static#home'

  get '/home' => 'static#home'
  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  delete '/signout' => 'sessions#destroy'
  get '/about' => 'static#about'
  get '/contact' => 'static#contact'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  before_save { self.email = email.downcase }
  before_create :create_remember_token

  validates :name, presence: true, length: { in: 2..50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private 

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :already_signed_in, only: [:new]


  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
  
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update, :index]
  before_action :already_signed_in, only: [:new]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy, :index]

  def index
    @users = User.paginate(page: params[:page], :per_page => 10)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to my Activity Page!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  def update
    if @user.authenticate(user_params[:password]) != false
      if @user.update_attributes(user_params)
        flash[:success] = "Profile updated"
        redirect_to @user
      else
        render 'edit'
      end
    else
      @user.errors[:base] << "Authentication failed, password incorrect"
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  #Before filters

  def signed_in_user
    unless signed_in?
      store_location
      flash[:warning] = "Please sign in"
      redirect_to signin_url 
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "Base Title"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
  
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def already_signed_in
    if signed_in? && current_user.admin == false
      redirect_to(current_user)
    end
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end
  

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def admin_user?
    !current_user.admin?
  end
  
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper

  #Returns gravatar (gravatar.com) for given user:
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://github.com/canalesb93/SkeletonApplication">Skeleton Application</a>
    by Ricardo Canales
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav id="navbar" class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "brand", root_path, id: "logo", class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="btn-group btn-toggle hidden-xs" style="margin-top: 14px;">
          <button id="on-btn"class="btn btn-xs btn-default">Static</button>
          <button id="off-btn"class="btn btn-xs btn-primary active">Fixed</button>
        </li>
        <% if signed_in? %>
          <% unless admin_user? %>
            <li><%= link_to "Users", users_path %></li>
          <% end %>
          <li id="fat-menu" class="dropdown">
            <a href='#' class="dropdown-toggle" data-toggle="dropdown">Account<span class="caret"></span></a>
            <ul class="dropdown-menu" role="dropdown">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign out", signout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
        <% end %>  
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 
                                              'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
    <!-- The form contains <%= pluralize(@user.errors.count, "error") %>. -->
      <ul class="list-unstyled">
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %>.</li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages' %>
<%= f.text_field :name, class: "form-control", 
                        placeholder: "Name",
                        required: true,
                        "data-parsley-minlength" => "2",
                        "data-parsley-trigger" => 'blur' %>

<%= f.text_field :email, class: "form-control",
                         placeholder: "Email",
                         required: true,
                         "data-parsley-type" => "email",
                         "data-parsley-trigger" => 'blur' %>

<%= f.password_field :password, class: "form-control",
                                placeholder: "Password",
                                required: true,
                                "data-parsley-minlength" => "6",
                                "data-parsley-trigger" => 'blur' %>

<%= f.password_field :password_confirmation, class: "form-control",
                                             placeholder: "Confirm Password",
                                             required: true,
                                             "data-parsley-minlength" => "6", 
                                             "data-parsley-equalto"=>"#user_password", 
                                             "data-parsley-trigger" => 'blur' %>
                                             
<!-- <div class="checkbox">
  <label>
    <input type="checkbox">Recieve friendly emails.
  </label>
</div> -->

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <div style="margin-top: 8px;">
    <%= link_to user.name, user %>
    <div class="pull-right">
      <% if current_user.admin? && !current_user?(user) %>
        <%= link_to "delete", user, method: :delete,
                                    data: { confirm: "Are you sure?" },
                                    class: "btn btn-danger"%>
      <% end %>
    </div>
  </div>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit') %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="center">Update your profile.</h1>
    <hr>
    <div class="row well">
      <div class="col-md-4">
        <%= gravatar_for @user, size: 150 %>
      </div>
      <div class="col-md-8 ">
        Your avatar is displayed through <abbr title="Globally Recognized Avatar">Gravatar</abbr>, a service which provides your avatars to be associated with your email address.
        <hr>
        <a type="button" class="btn btn-default pull-right" href="http://gravatar.com/emails" target="_blank"style="margin-top: 10px;">Change profile picture</a>
      </div>
    </div>
    <hr>
    <%= form_for @user, html: { 'data-parsley-validate' => '', 'id' => 'update_form' } do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>

      <div class="input-group">
        <%= f.text_field :name, class: "form-control", 
                                placeholder: "Name",
                                "data-parsley-minlength" => "2",
                                required: true,
                                disabled: true,
                                "data-parsley-group" => 'input1',
                                "data-parsley-errors-container"=>'#name_error_container' %>
        <span class="input-group-btn">
          <span id="edit-name" class="btn btn-primary">Edit</span>
        </span>
      </div>
      <div id="name_error_container"></div>

      <%= f.label :email %>
      <div class="input-group">
        <%= f.text_field :email, class: "form-control",
                                 placeholder: "Email",
                                 required: true,
                                 disabled: true,
                                 "data-parsley-type" => "email",
                                 "data-parsley-group" => 'input2',
                                 "data-parsley-errors-container"=>'#email_error_container'%>
        <span class="input-group-btn">
          <span id="edit-email" class="btn btn-primary">Edit</span>
        </span>
      </div>
      <div id="email_error_container"></div> 

      <hr>
      <div id="update_confirmation" hidden>
        <div class="alert alert-warning">Please input your password to verify changes.</div>
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control",
                                        placeholder: "Password",
                                        required: true,
                                        "data-parsley-minlength" => "6",
                                        "data-parsley-trigger" => 'blur' %>

        <%= f.hidden_field :password_confirmation, class: "form-control",
                                                     placeholder: "Confirm Password",
                                                     required: true,
                                                     "data-parsley-minlength" => "6", 
                                                     "data-parsley-equalto"=>"#user_password", 
                                                     "data-parsley-trigger" => 'blur' %>
      </div>
      <!-- <div class="checkbox">
        <label>
          <input type="checkbox">Recieve friendly emails.
        </label>
      </div> -->
      <%= f.submit "Save changes", class: "long btn btn-large btn-primary" %>
    <% end %> 
    <hr>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<h1>All users</h1>

<div class="center"><%= will_paginate %></div>
  <ul class="users">
    <%= render @users %>
  </ul>
<div class="center"><%= will_paginate %></div>

app/views/users/new.html.erb
<% provide(:title, 'Registration') %>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h1 class="center">Sign up</h1>
    <%= form_for @user, html: { 'data-parsley-validate' => '' } do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Create my account", class: "long btn btn-large btn-primary" %>
    <% end %>
      <br>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde praesentium nesciunt omnis, porro culpa. Facilis repellat accusamus adipisci quae qui sapiente voluptate ipsam voluptatem natus in atque asperiores, tenetur minima maiores necessitatibus eum est obcaecati quibusdam esse doloribus sequi excepturi aut quod et! Recusandae voluptas velit necessitatibus, nemo quasi voluptatem eum aliquid inventore quidem nobis, repellendus quibusdam, a cum error rerum! Enim amet eligendi, placeat voluptas voluptatem ut, soluta nulla alias quis. Quia totam nemo assumenda libero dolores placeat, nihil inventore deleniti, repudiandae cumque incidunt provident sint qui ex aliquam, dignissimos odio hic, minus architecto adipisci quae vero? Nemo, provident.</p>  
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>